my_profile_name:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: valued-context-474807-t7
      dataset: gz_raw_data
      location: EU
      threads: 4